### ISSUE TITLE
Is it possible to choose what side the new window appears on when using vsplit to open?

### ISSUE THREAD

**Issue by npearson72** [weirongxu/coc-explorer#179]
It currently opens on the right side. I would prefer it was on the left of my existing buffer window.

**Comment by weirongxu** [comment]
This should be fixed by https://github.com/weirongxu/coc-explorer/pull/257, you can use `h 'splitright'` to control the behavior or vsplit

**Comment by npearson72** [comment]
Sorry, a little confused. Where do I add this?

I added this to my coc-settings.json

```
  "explorer.keyMappings": {
    "v": "open:vsplitright"
  },
```

But I get this error:

`[coc.nvim] TypeError: h[(intermediate value)(intermediate value)(intermediate value)] is not a function`

**Comment by npearson72** [comment]
Ok, I think I see... this is a global vim setting?

I added: `set nosplitright`

But when I use the `E` shortcut to open:

```
"E": "open:vsplit",
```

It does not work?

I also tried: `set splitright`

Can you explain what I am doing wrong?

**Comment by weirongxu** [comment]
I just released a new version, you should upgrade first, and then try `set splitright`.

**Comment by npearson72** [comment]
I am using `coc-explorer@0.7.29`.

I want the vsplit to open on the left, not the right. The right was always the default behavior.

Anyway, still not working.

**Comment by npearson72** [comment]
Oh, never mind. It does work now. Indeed setting to `set nosplitright` works!

Thank you! 🥳
