### ISSUE TITLE
[BUG]no color/highlight in coc-explorer

### ISSUE THREAD

**Issue by krisfans** [weirongxu/coc-explorer#500]
**Describe the bug**

no color/highlight in coc-explorer, just as  as the picture shows
![Snipaste_2022-01-18_19-19-59](https://user-images.githubusercontent.com/57793534/149928113-600abdaf-d089-4c01-82f9-dbbeee9acb79.png)

**Result from CocInfo**

```md
## versions

vim version: NVIM v0.6.0
node version: v15.14.0
coc.nvim version: 0.0.80-b56c7369b0
coc.nvim directory: /home/kris/.cache/nvim/dein/repos/github.com/neoclide/coc.nvim_release
term: xterm-256color
platform: linux

## Log of coc.nvim

2022-01-18T19:17:46.171 INFO (pid:17973) [services] - registered service "highlight"
2022-01-18T19:17:46.230 INFO (pid:17973) [plugin] - coc.nvim initialized with node: v15.14.0 after 214ms
2022-01-18T19:17:51.517 INFO (pid:17973) [attach] - receive notification: showInfo []
```

**Steps to reproduce**
1. `nvim -u minimal.vim`
2. `:CocCommand explorer `
3. See error
 
```vim
if &compatible
    set nocompatible               " Be iMproved
endif
set runtimepath^=~/.cache/nvim/dein/repos/github.com/neoclide/coc.nvim_release
filetype plugin indent on
syntax enable
set background=dark
set termguicolors
" colorscheme gruvbox8


autocmd BufRead,BufNewFile *.tex set filetype=tex

set completeopt-=preview

    let g:coc_global_extensions =[
        \ 'coc-clangd',
        \ 'coc-texlab',
        \ 'coc-explorer',
        \ ]
```

**Screenshots**

**Comment by weirongxu** [comment]
Have you tried upgrading to the latest coc-explorer? I just fix a bug about the highlight. https://github.com/weirongxu/coc-explorer/issues/499

**Comment by krisfans** [comment]
> Have you tried upgrading to the latest coc-explorer? I just fix a bug about the highlight. #499

Fixed, Thanks

**Comment by ranelpadon** [comment]
@weirongxu I have similar issue after upgrading `coc`. How am I supposed to update the `coc-explorer`? Seems still not working on my end.

My `coc` plugin:
```viml
Plug 'neoclide/coc.nvim', {'branch': 'release'}
```

then, I did `:CocUpdate` and `CocUpdateSync`:
<img width="373" alt="Screen Shot 2022-01-27 at 5 58 10 AM" src="https://user-images.githubusercontent.com/4292088/151254147-f538732f-b911-4602-85d4-3ceb8f3a0048.png">

However, the `coc-explorer` still has no colors:
<img width="193" alt="Screen Shot 2022-01-27 at 5 58 28 AM" src="https://user-images.githubusercontent.com/4292088/151254218-b5362c86-d3f9-497c-9961-fb5bf4f8df8b.png">

Am I missing something? What additional steps I could take to debug/fix it? Thanks

**Comment by weirongxu** [comment]
> @weirongxu I have similar issue after upgrading `coc`. How am I supposed to update the `coc-explorer`? Seems still not working on my end.
> 
> My `coc` plugin:
> 
> ```viml
> Plug 'neoclide/coc.nvim', {'branch': 'release'}
> ```
> 
> then, I did `:CocUpdate` and `CocUpdateSync`: <img alt="Screen Shot 2022-01-27 at 5 58 10 AM" width="373" src="https://user-images.githubusercontent.com/4292088/151254147-f538732f-b911-4602-85d4-3ceb8f3a0048.png">
> 
> However, the `coc-explorer` still has no colors: <img alt="Screen Shot 2022-01-27 at 5 58 28 AM" width="193" src="https://user-images.githubusercontent.com/4292088/151254218-b5362c86-d3f9-497c-9961-fb5bf4f8df8b.png">
> 
> Am I missing something? What additional steps I could take to debug/fix it? Thanks

1. Upgrade coc.nvim first.
2. If you were using neovim nightly, please upgrade neovim, the nightly version will have some breaking changes.

**Comment by ranelpadon** [comment]
@weirongxu 

1. Already updated the `coc.nvim`. I accidentally updated it using `PlugUpdate` which updates all plugins which triggered the error. I have no intention of updating it actually.

2. Yes, I noticed also that it's working on my `MacVim` and `Vim`, but not on `Neovim`. I'm using the nightly builds (` v0.6.0-dev+nightly-430-gc642f3ac2`), so updated with latest nightly last night,  but it has build issue in my local. So, I just used the official, stable release (`v0.6.1`) this morning, and it worked after that! 

Thanks for your suggestion though! :)
